export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Aparna Chauhan",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Jan Doe",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Monica Mittal",
  },
  {
    id:4,
    profilePicture: "assets/person/parth.jpg",
    username: "Parth Sharma",
  },
  {
    id:5,
    profilePicture: "assets/person/arya.jpg",
    username: "Arya mukharjee",
  },
  {
    id:6,
    profilePicture: "assets/person/lav.jpg",
    username: "Lavkush Singhania",
  },
  {
    id:7,
    profilePicture: "assets/person/naman.jpg",
    username: "Naman Kumar",
  },
  {
    id:8,
    profilePicture: "assets/person/nis.jpg",
    username: "Nishidh Gautam",
  },
  {
    id:9,
    profilePicture: "assets/person/8.jpeg",
    username: "Nimisha Saxena",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Nitya bansal",
  },
  {
    id:11,
    profilePicture: "assets/person/Dp.jpg",
    username: "Pradip Kumar Singh",
  },
  {
    id:12,
    profilePicture: "assets/person/9.jpeg",
    username: "Alexa baker",
  },
];

export const Posts = [
  {
    id: 11,
    photo: "assets/post/11.png",
    date: "2 week ago",
    userId: 11,
    like: 362,
    comment: 4,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
 
  {
    id: 12,
    photo: "assets/post/12.jpg",
    date: "2 days ago",
    userId: 12,
    like: 43,
    comment: 6,
  },
];
